baseURL: https://hauschelmedia.com/
languageCode: en-us
build:
  writeStats: true
title: Alexander Hauschel's Portfolio
# Uncomment below to use aafu as hugo theme. See instructions in README.md
theme: aafu

permalinks:
    posts: /:year/:month/:slug/
    page: /:slug/
    blog : /blog/:slug/

params:
  author: Alexander Hauschel
  description: Portfolio
  copyright: >
    - Last updated: 2025-08-22
  theme:
    mainTheme: dark
    showAttribute: false
    singlePage: false  

  profile:
    name: "Alex Hauschel"
    tagline: Lifelong Learner
    location: "Sarasota, FL"
    photo: /static/img/profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/alexanderhauschel/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/amhcoding"
        title: GitHub
      - icon: fab fa-twitter
        url: "https://x.com/ubexhd"
        title: X (Twitter)
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Hello! I am a 26 year old designer based in Sarasota, FL.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Multimedia Designer
        dates: 2023 - *Present*
        company: Kidde Global Solutions
        url: "https://www.kiddeglobalsolutions.com/"
        details: |1-
          - Printed from desktop. Sent [emails](#).
              - Called people *using* telephone.
          - Drank water from office cooler.
          - Ate donuts on people's birthdays.
      - position: Video Production Intern
        dates: 2022 - 2023
        url: "https://www.trane.com/commercial/north-america/us/en/education-training/trane-university.html"
        company: Trane Technologies
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: B.S. in Information Systems
        college: University of Wisconsin-La Crosse
        dates: 2018-2023
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Journal Articles
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Journal Articles
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Project 1
        url: "#"
        description: Description of the project
      - title: Project 2
        url: "#"
        description: Description of the project
      - title: Project 3
        url: "#"
        description: Description of the project
      - title: Project 4
        url: "#"
        description: Description of the project
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Empathy
        skillrating: 95
      - skill: Collaboration
        skillrating: 80
      - skill: Problem-solving
        skillrating: 80
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Beach volleyball
      - hobby: Pickleball
      - hobby: Video games
      - hobby: Line dancing
